# Copyright 2020 Alex Harvill
# SPDX-License-Identifier: Apache-2.0
'''
tweak xcode projects generated by cmake and edited by cocoapods
'''
import logging
from pathlib import Path
try:
  import pbxproj
except ImportError:
  pbxproj = None


def update_pod_paths(build_dir, project_file):
  'fix broken relative paths to cocoapods .xcconfig files'
  project = pbxproj.XcodeProject.load(str(project_file))

  pod_config_files = []
  for file_ref in project.objects.get_objects_in_section('PBXFileReference'):
    if file_ref.get_name().endswith('.xcconfig'):

      if '/Pods/' in file_ref.path:
        pod_config_files.append(file_ref)
        parts = file_ref.path.split('/Pods/')
        assert len(parts) == 2, 'no .../Pods/... path for' + file_ref.get_name()
        new_path = build_dir / 'Pods' / parts[1]
        assert new_path.exists()
        logging.info('config:%s', file_ref.get_name())
        logging.info('  old path:%s', file_ref.path)
        logging.info('  new path:%s', new_path)
        file_ref.path = str(new_path)

  project.save()


if __name__ == '__main__':
  _build_dir = Path('/Users/Shared/vt/build/dev_ios/unlock')
  _project_file = _build_dir / 'unlock_root.xcodeproj' / 'project.pbxproj'
  update_pod_paths(_build_dir, _project_file)
