# Copyright 2020 Alex Harvill
# SPDX-License-Identifier: Apache-2.0

set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED "NO")
set(MACOSX_BUNDLE_GUI_IDENTIFIER "com.org.test")
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "")
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_STYLE "Manual")
set(CMAKE_XCODE_ATTRIBUTE_ORGANIZATIONNAME "Org Name.")


# xcode sets these by default therefore cmake needs to also
SET(CMAKE_Swift_FLAGS_DEBUG "${CMAKE_Swift_FLAGS_DEBUG} -DDEBUG")
SET(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -DDEBUG")
SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -DDEBUG")
